language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t tanya0410/docker-react -f Dockerfile.dev .  

scripts:
  - docker run -e CI=true tanya0410/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dDocker-react"
  env: "Ddockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-304156220123"
  bucket_path: "dDocker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY