language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t tanya0410/docker-react -f Dockerfile.dev .  

scripts:
  - docker run -e CI=true tanya0410/docker-react npm run test

